services:
  twitchirchub:
    build: .
    container_name: TwitchIrcHub
    #env_file:
    #  - .env
    environment:
      - Logging__Console__FormatterName=
    #network_mode: bridge
    #volumes:
    #  - /var/run/mysqld/mysqld.sock:/root/mysqld.sock:rw
    ports:
      - "4720:8080"
    networks:
      - mariadbnetwork
    restart: unless-stopped

networks:
  mariadbnetwork:
    name: "mariadbnetwork"
    external: true
